// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pvsCollector.Data;

#nullable disable

namespace pvsCollector.Data.Migrations
{
    [DbContext(typeof(pvsCollectorContext))]
    partial class pvsCollectorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pvsCollector.Data.Entities.Inverter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("WrittenAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("freqHz")
                        .HasColumnType("real");

                    b.Property<float>("i3phsumA")
                        .HasColumnType("real");

                    b.Property<float>("iMppt1A")
                        .HasColumnType("real");

                    b.Property<float>("ltea3phsum")
                        .HasColumnType("real");

                    b.Property<string>("msmtEps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("p3phsumKw")
                        .HasColumnType("real");

                    b.Property<float>("pMppt1Kw")
                        .HasColumnType("real");

                    b.Property<string>("prodMdlNm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("tHtsnkDegc")
                        .HasColumnType("int");

                    b.Property<float>("vMppt1V")
                        .HasColumnType("real");

                    b.Property<float>("vln3phavgV")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("sn");

                    b.ToTable("Inverters");
                });

            modelBuilder.Entity("pvsCollector.Data.Entities.Meter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("WrittenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ctSclFctr")
                        .HasColumnType("int");

                    b.Property<float>("freqHz")
                        .HasColumnType("real");

                    b.Property<float>("i1A")
                        .HasColumnType("real");

                    b.Property<float>("i2A")
                        .HasColumnType("real");

                    b.Property<string>("msmtEps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("negLtea3phsumKwh")
                        .HasColumnType("real");

                    b.Property<float>("netLtea3phsumKwh")
                        .HasColumnType("real");

                    b.Property<float>("p1Kw")
                        .HasColumnType("real");

                    b.Property<float>("p2Kw")
                        .HasColumnType("real");

                    b.Property<float>("p3phsumKw")
                        .HasColumnType("real");

                    b.Property<float>("posLtea3phsumKwh")
                        .HasColumnType("real");

                    b.Property<string>("prodMdlNm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("q3phsumKvar")
                        .HasColumnType("real");

                    b.Property<float>("s3phsumKva")
                        .HasColumnType("real");

                    b.Property<string>("sn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("totPfRto")
                        .HasColumnType("real");

                    b.Property<float>("v12V")
                        .HasColumnType("real");

                    b.Property<float>("v1nV")
                        .HasColumnType("real");

                    b.Property<float>("v2nV")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("sn");

                    b.ToTable("Meters");
                });
#pragma warning restore 612, 618
        }
    }
}
